### ISSUE TITLE
vkmark: test阶段会Segmentation fault

### ISSUE THREAD

**Issue by RevySR** [XUANTIE-RV/gcc#14]
c910v环境

源码
```
https://deb.debian.org/debian/pool/main/v/vkmark/vkmark_2017.08+git20220909-1.dsc
```

崩溃栈
```
(gdb) bt
#0  0x0000003ff7456bd4 in __GI___libc_free (mem=0x474e5543432b2b00) at malloc.c:3362
#1  0x0000002aaab40134 in stbi_image_free (retval_from_stbi_load=<optimized out>) at ../src/stb_image.h:938
#2  0x0000002aaab44b2c in Util::Image::~Image (this=<optimized out>, __in_chrg=<optimized out>) at ../src/util.cpp:105
#3  0x0000002aaab44cb6 in Util::read_image_file (rel_path="non_existent.txt") at ../src/util.cpp:145
#4  0x0000002aaab2dfea in C_A_T_C_H_T_E_S_T_0 () at ../tests/util_image_file_test.cpp:87
#5  0x0000002aaaac8716 in Catch::TestInvokerAsFunction::invoke (this=<optimized out>) at ../tests/catch.hpp:14332
#6  Catch::TestCase::invoke (this=<optimized out>) at ../tests/catch.hpp:14171
#7  Catch::RunContext::invokeActiveTestCase (this=this@entry=0x3ffffff360) at ../tests/catch.hpp:13027
#8  0x0000002aaaadd4bc in Catch::RunContext::runCurrentTest (this=this@entry=0x3ffffff360, redirectedCout="", redirectedCerr="")
    at ../tests/catch.hpp:13000
#9  0x0000002aaaae7f46 in Catch::RunContext::runTest (this=this@entry=0x3ffffff360, testCase=...) at ../tests/catch.hpp:12761
#10 0x0000002aaaae96d8 in Catch::(anonymous namespace)::TestGroup::execute (this=0x3ffffff350) at ../tests/catch.hpp:13354
#11 Catch::Session::runInternal (this=this@entry=0x3ffffff638) at ../tests/catch.hpp:13564
#12 0x0000002aaaae9b58 in Catch::Session::run (this=this@entry=0x3ffffff638) at ../tests/catch.hpp:13520
#13 0x0000002aaaac1156 in Catch::Session::run<char> (argv=0x3ffffff988, argc=1, this=0x3ffffff638) at ../tests/catch.hpp:13238
#14 Catch::Session::run<char> (argv=0x3ffffff988, argc=1, this=0x3ffffff638) at ../tests/catch.hpp:13233
#15 main (argc=<optimized out>, argv=0x3ffffff988) at ../tests/catch.hpp:17537
```

malloc 3362:
```
https://github.com/revyos/glibc/blob/revyos-2.36/malloc/malloc.c#L3362
```

gcc 10.4 / 13 failed

**Comment by RevySR** [comment]
强制降级libstdc++6=13.1.0-6 gcc-13-base=13.1.0-6 libgcc-s1=13.1.0-6 可以通过测试

**Comment by RevySR** [comment]
强制降级libstdc++6=13.2.0-4revyos1 gcc-13-base=13.2.0-4revyos1 libgcc-s1=13.2.0-4revyos1 可以通过测试

13.2.0-4revyos1 与 13.2.0-4revyos2 区别
后者开了xthead扩展

**Comment by RevySR** [comment]
关联问题：
test-c910v镜像
强制降级libstdc++6=13.2.0-4revyos1 gcc-13-base=13.2.0-4revyos1 libgcc-s1=13.2.0-4revyos1 后 

libreoffice不崩溃了

**Comment by RevySR** [comment]
关联问题：
https://deb.debian.org/debian/pool/main/r/rnp/rnp_0.17.0-3.dsc

rnp编译测试也有相同问题 降级通过

**Comment by RevySR** [comment]
https://github.com/revyos/gcc/commit/b2ef0db0656aa864ca7d7b07c9969fbf8c2897c9

rnp/vkmark测试项都通过

libreoffice待测

**Comment by RevySR** [comment]
libreoffice 测试通过
